### PR TITLE
rename TOKEN_MERGE to TOKEN_UPDATE

### PR DESCRIPTION
**Pull request by zimbatm**
according to src/libexpr/lexer.l, nix calls `//` the UPDATE token

see https://github.com/nixos/nix/blob/f435634a29551754d5f7303b0a60cd8fe2df2079/src/libexpr/lexer.l#L122

### CODE REVIEW

**Comment by zimbatm** [comment]
There are probably a few more of those but I wanted to start somewhere.

Are you waiting for me to merge the PR or do you want to do it yourself?

**Comment by zimbatm** [comment]
also renamed the Kind to match the token name

**Comment by jD91mZM2** [comment]
I was waiting in case @matklad had any thoughts since you asked him to review too. Will merge.

**Comment by zimbatm** [comment]
it was more to keep him in the loop. see also #2 for a more general ticket to track the differences.

**Pull request merged**
